In [14]:
import numpy as np

In [15]:
grid=[[1,2,3,0,0,0,0,0,0], [1,0,3,7,0,0,0,0,0], [0,2,3,0,0,0,0,0,8],
      [0,0,7,0,0,0,0,0,0], [6,0,4,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]

## Define the function Possibility

## Define Possible Solutions and block non possible ones with False

In [29]:
def possible(row, column, number):
    global grid
### Check rows
    for i in range(0,9):
        if grid[row][i]==number:
            return False

    
## Check Columns
    for i in range(0,9):
        if grid[i][column]==number:
            return False

    
### Check 3-> Check Squares & define co- ordinates
    x0=column//3*3
    y0==row//3*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[x0+i][y0+j]==number:
                return False
    return True

 ## What Happened in Earlier Function
### Basically we blocked non possible solutions with False, so if it is true the unsolved cell will be kept as 0 or unsolved for check against the given 'number'

### Step 1 in solve function-> 
#### if for a cell all possible checks returns non False ie; cell= number is not False , keep the cell as number ( remember it is one of the possibilities in ascending order
#### Next go solve the next 0. Now if in this 0 you encounter False or dupliacy for all 'numbers' 1 to 9-> backtrack to previous step and then previous and so on else move on to next unsolved cell

In [32]:
def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0

                return
    solve()

In [37]:
print(np.matrix(grid))

[[1 2 3 0 0 0 0 0 0]
 [1 0 3 7 0 0 0 0 0]
 [0 2 3 0 0 0 0 0 8]
 [0 0 7 0 0 0 0 0 0]
 [6 0 4 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [38]:
print('More solutions')

More solutions
